# Generated by Django 5.0.2 on 2024-03-05 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=1024)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceCode', models.CharField(max_length=30)),
                ('referenceLink', models.CharField(blank=True, max_length=1024, null=True)),
                ('destName', models.CharField(max_length=100)),
                ('destCity', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coccinella.saleschannel')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('measure', models.CharField(choices=[('m', 'Meter'), ('cm', 'Centimeter'), ('m²', 'Squared meter'), ('p', 'Piece')], default='p', max_length=5)),
                ('sellable', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('resources', models.ManyToManyField(blank=True, through='coccinella.SourceItem', to='coccinella.stockitem')),
            ],
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='coccinella.stockitem'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resources_set', to='coccinella.stockitem'),
        ),
        migrations.CreateModel(
            name='StockSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='coccinella.stockitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coccinella.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='coccinella.StockSale', to='coccinella.stockitem'),
        ),
    ]
